#!/usr/bin/env bash
# This script lists files in the current directory showing only the part after the first dash (-)

for file in *; do
  if [[ "$file" == *-* ]]; then
    echo "$file" | cut -d '-' -f 2-
  fi
done
